import { useState } from "react";
import {
  authActions,
  notificationActions,
  ServiceError,
  useAuth,
  useRpcMutation,
  useRpcQuery,
  useTheme,
} from "sunbeam-g2v";
import { ElizaService } from "./gen/connectrpc/eliza/v1/eliza_pb";
import "./app.css";

export function App() {
  const { theme, toggle } = useTheme();
  const { isAuthenticated, claims } = useAuth();
  const [tokenInput, setTokenInput] = useState("");
  const [draft, setDraft] = useState("Hello, Eliza.");
  const [warmupSentence] = useState("Are you a real therapist?");

  // Unary query: fires once, refetched manually. Uses the typed Eliza client
  // generated by `buf generate` from proto/connectrpc/eliza/v1/eliza.proto.
  const warmup = useRpcQuery(
    ElizaService,
    "say",
    { sentence: warmupSentence },
    { staleTime: Infinity },
  );

  // Unary mutation: send sentence, await reply. Demonstrates the same client
  // surface for write-shaped RPCs.
  const say = useRpcMutation(ElizaService, "say");

  const handleLogin = () => {
    const token = tokenInput.trim();
    if (!token) {
      notificationActions.push({
        level: "warning",
        title: "paste a token to log in",
        ttlMs: 3_000,
      });
      return;
    }
    authActions.loginSuccess({
      accessToken: token,
      claims: { sub: "demo-user" },
    });
    notificationActions.push({
      level: "success",
      title: "logged in",
      ttlMs: 2_000,
    });
  };

  return (
    <main data-theme={theme === "dark" ? "dark" : "light"}>
      <header>
        <h1>sunbeam-g2v · simple</h1>
        <button onClick={toggle}>theme: {theme}</button>
      </header>

      <section>
        <h2>connectrpc — ElizaService.Say (warmup query)</h2>
        <p>
          <code>useRpcQuery(ElizaService, "say", &#123; sentence &#125;)</code>
        </p>
        <Pretty
          data={warmup.data}
          error={warmup.error}
          loading={warmup.isLoading}
        />
        <button onClick={() => warmup.refetch()}>refetch</button>
      </section>

      <section>
        <h2>connectrpc — ElizaService.Say (mutation)</h2>
        <p>
          <code>useRpcMutation(ElizaService, "say")</code>
        </p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            say.mutate({ sentence: draft });
          }}
        >
          <input
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            size={48}
            placeholder="say something to Eliza"
          />
          <button type="submit" disabled={say.isPending}>
            {say.isPending ? "…" : "send"}
          </button>
        </form>
        <Pretty
          data={say.data}
          error={say.error}
          loading={say.isPending}
        />
      </section>

      <section>
        <h2>auth — withAuth interceptor</h2>
        {isAuthenticated ? (
          <>
            <p>
              authenticated as <code>{claims?.sub ?? "<unknown>"}</code>; the{" "}
              <code>withAuth</code> interceptor will inject this Bearer on every
              RPC.
            </p>
            <button onClick={() => authActions.logout()}>logout</button>
          </>
        ) : (
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleLogin();
            }}
          >
            <input
              placeholder="paste any string — Eliza ignores it"
              value={tokenInput}
              onChange={(e) => setTokenInput(e.target.value)}
              size={48}
            />
            <button type="submit">login</button>
          </form>
        )}
      </section>
    </main>
  );
}

function Pretty({
  data,
  error,
  loading,
}: {
  data: unknown;
  error: unknown;
  loading?: boolean;
}) {
  if (loading) return <pre>…</pre>;
  if (error) {
    const svc = error instanceof ServiceError ? error : ServiceError.from(error);
    return (
      <pre className="error">
        {svc.kind}: {svc.message}
      </pre>
    );
  }
  if (data === undefined) return <pre>—</pre>;
  return <pre>{JSON.stringify(data, null, 2)}</pre>;
}
