// SPDX-License-Identifier: AGPL-3.0-or-later
syntax = "proto3";

package ory.keto.relation_tuples.v1alpha2;

import "ory/keto/relation_tuples/v1alpha2/relation_tuples.proto";
import "google/protobuf/field_mask.proto";

option go_package = "github.com/ory/keto/proto/ory/keto/relation_tuples/v1alpha2;rts";
option csharp_namespace = "Ory.Keto.RelationTuples.v1alpha2";
option java_multiple_files = true;
option java_outer_classname = "ReadServiceProto";
option java_package = "sh.ory.keto.relation_tuples.v1alpha2";
option php_namespace = "Ory\\Keto\\RelationTuples\\v1alpha2";

service ReadService {
  rpc ListRelationTuples(ListRelationTuplesRequest) returns (ListRelationTuplesResponse);
}

message ListRelationTuplesRequest {
  message Query {
    string namespace = 1;
    string object = 2;
    string relation = 3;
    Subject subject = 4;
  }
  Query query = 1 [deprecated = true];
  RelationQuery relation_query = 6;
  google.protobuf.FieldMask expand_mask = 2;
  string snaptoken = 3;
  int32 page_size = 4;
  string page_token = 5;
}

message ListRelationTuplesResponse {
  repeated RelationTuple relation_tuples = 1;
  string next_page_token = 2;
}
